### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by drneals** [segler-alex/rhythmbox-radio-browser#12]
I installed the software in Ubuntu 10.04 using the Synaptic Package Manager and everything looks fine there but there is nothing in Rhythmbox.  How do I start troubleshooting.  I am an Ubuntu novice.

**Comment by fieldse** [comment]
Hi dmeals - you have to enable the plugin in rhthmbox. Edit > plugins: place checkbox by "internet radio browser"

**Comment by fieldse** [comment]
comment: Might be a good idea to have this plugin somehow auto-set this option for people, it threw me for a loop too.

**Comment by segler-alex** [comment]
the new version on the homepage has this feature.

**Comment by virtualeyes** [comment]
I made the mistake of installing as root, doh!  Rhythm box obviously runs under logged in user, so plugin did not display in list ;--)
