### ISSUE TITLE
Doesn't work with 0.13.1

### ISSUE THREAD

**Issue by hrhenry** [segler-alex/rhythmbox-radio-browser#16]
It was working fine with 0.12, but I upgraded to 0.13.1 and now it shows as installed, but doesn't actually show up in the left side pane.

**Comment by segler-alex** [comment]
please add more information on what plugin version you are using, your linux distribution, ...

**Comment by hrhenry** [comment]
Your latest version with Rhythmbox 0.13.1, Lucid. 

Doesn't matter anymore. I reverted back to 0.12.8. Maybe when I have more time I'll play around with it some more.

**Comment by segler-alex** [comment]
problem solved by ubuntu people and added to upstream
