### ISSUE TITLE
Wrong country for french radio

### ISSUE THREAD

**Issue by Cameleon** [segler-alex/rhythmbox-radio-browser#7]
I have just seen that some French radio are affected to the country "France" (like NRJ), but others are affected to "France/F" (like France Inter) and consequently doesn't appear in the county list.

**Comment by segler-alex** [comment]
could you describe this error better. i was not able to reproduce it.

**Comment by Cameleon** [comment]
Hi,
In this image, France Inter doesn't appear in the list of French radio:
http://pix.toile-libre.org/?img=1274728325.png
I suppose that this is because in the list where it is recorded, it as the property France/F.
However, I do not really understand why there is 2 lists for the country (into "Board" and "Local"), this is not very clear...

**Comment by segler-alex** [comment]
i think i do understand you now :)

let me explain: local, board are not the same! local is created by me alone. board is from somewhere else in the internet. everybody (also you) can post a new station to board. so stations in local do not have to be in board!

**Comment by Cameleon** [comment]
Hum, ok, its more clear now, thanks!
